//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficTrain.ServiceInfoTrainAll {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainEvent", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses")]
    [System.SerializableAttribute()]
    public partial class TrainEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CWagCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrewStTimeHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrewStTimeMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DObjNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DObjTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GrWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachinistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessIdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeibStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NtWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainIdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberSuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CWagCount {
            get {
                return this.CWagCountField;
            }
            set {
                if ((this.CWagCountField.Equals(value) != true)) {
                    this.CWagCountField = value;
                    this.RaisePropertyChanged("CWagCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrewStTimeH {
            get {
                return this.CrewStTimeHField;
            }
            set {
                if ((this.CrewStTimeHField.Equals(value) != true)) {
                    this.CrewStTimeHField = value;
                    this.RaisePropertyChanged("CrewStTimeH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrewStTimeM {
            get {
                return this.CrewStTimeMField;
            }
            set {
                if ((this.CrewStTimeMField.Equals(value) != true)) {
                    this.CrewStTimeMField = value;
                    this.RaisePropertyChanged("CrewStTimeM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DObjName {
            get {
                return this.DObjNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DObjNameField, value) != true)) {
                    this.DObjNameField = value;
                    this.RaisePropertyChanged("DObjName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DObjType {
            get {
                return this.DObjTypeField;
            }
            set {
                if ((this.DObjTypeField.Equals(value) != true)) {
                    this.DObjTypeField = value;
                    this.RaisePropertyChanged("DObjType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestStation {
            get {
                return this.DestStationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestStationField, value) != true)) {
                    this.DestStationField = value;
                    this.RaisePropertyChanged("DestStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestType {
            get {
                return this.DestTypeField;
            }
            set {
                if ((this.DestTypeField.Equals(value) != true)) {
                    this.DestTypeField = value;
                    this.RaisePropertyChanged("DestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventAxis {
            get {
                return this.EventAxisField;
            }
            set {
                if ((object.ReferenceEquals(this.EventAxisField, value) != true)) {
                    this.EventAxisField = value;
                    this.RaisePropertyChanged("EventAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventStation {
            get {
                return this.EventStationField;
            }
            set {
                if ((object.ReferenceEquals(this.EventStationField, value) != true)) {
                    this.EventStationField = value;
                    this.RaisePropertyChanged("EventStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((this.EventTimeField.Equals(value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrWeight {
            get {
                return this.GrWeightField;
            }
            set {
                if ((this.GrWeightField.Equals(value) != true)) {
                    this.GrWeightField = value;
                    this.RaisePropertyChanged("GrWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Machinist {
            get {
                return this.MachinistField;
            }
            set {
                if ((object.ReferenceEquals(this.MachinistField, value) != true)) {
                    this.MachinistField = value;
                    this.RaisePropertyChanged("Machinist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessIdn {
            get {
                return this.MessIdnField;
            }
            set {
                if ((this.MessIdnField.Equals(value) != true)) {
                    this.MessIdnField = value;
                    this.RaisePropertyChanged("MessIdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeibStation {
            get {
                return this.NeibStationField;
            }
            set {
                if ((object.ReferenceEquals(this.NeibStationField, value) != true)) {
                    this.NeibStationField = value;
                    this.RaisePropertyChanged("NeibStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NtWeight {
            get {
                return this.NtWeightField;
            }
            set {
                if ((this.NtWeightField.Equals(value) != true)) {
                    this.NtWeightField = value;
                    this.RaisePropertyChanged("NtWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainIdn {
            get {
                return this.TrainIdnField;
            }
            set {
                if ((this.TrainIdnField.Equals(value) != true)) {
                    this.TrainIdnField = value;
                    this.RaisePropertyChanged("TrainIdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumber {
            get {
                return this.TrainNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberField, value) != true)) {
                    this.TrainNumberField = value;
                    this.RaisePropertyChanged("TrainNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumberPrefix {
            get {
                return this.TrainNumberPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberPrefixField, value) != true)) {
                    this.TrainNumberPrefixField = value;
                    this.RaisePropertyChanged("TrainNumberPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumberSuffix {
            get {
                return this.TrainNumberSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberSuffixField, value) != true)) {
                    this.TrainNumberSuffixField = value;
                    this.RaisePropertyChanged("TrainNumberSuffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainWorking", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses")]
    [System.SerializableAttribute()]
    public partial class TrainWorking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StopTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainSuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MsType {
            get {
                return this.MsTypeField;
            }
            set {
                if ((this.MsTypeField.Equals(value) != true)) {
                    this.MsTypeField = value;
                    this.RaisePropertyChanged("MsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeStation {
            get {
                return this.NeStationField;
            }
            set {
                if ((object.ReferenceEquals(this.NeStationField, value) != true)) {
                    this.NeStationField = value;
                    this.RaisePropertyChanged("NeStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StopTime {
            get {
                return this.StopTimeField;
            }
            set {
                if ((this.StopTimeField.Equals(value) != true)) {
                    this.StopTimeField = value;
                    this.RaisePropertyChanged("StopTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Track {
            get {
                return this.TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackField, value) != true)) {
                    this.TrackField = value;
                    this.RaisePropertyChanged("Track");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumber {
            get {
                return this.TrainNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberField, value) != true)) {
                    this.TrainNumberField = value;
                    this.RaisePropertyChanged("TrainNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainPrefix {
            get {
                return this.TrainPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainPrefixField, value) != true)) {
                    this.TrainPrefixField = value;
                    this.RaisePropertyChanged("TrainPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainSuffix {
            get {
                return this.TrainSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainSuffixField, value) != true)) {
                    this.TrainSuffixField = value;
                    this.RaisePropertyChanged("TrainSuffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkMessage", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses")]
    [System.SerializableAttribute()]
    public partial class WorkMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CWagCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrewStTimeHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrewStTimeMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GrWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachinistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessIdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessPropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MessTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmSostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NtWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StDestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainIdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CWagCount {
            get {
                return this.CWagCountField;
            }
            set {
                if ((this.CWagCountField.Equals(value) != true)) {
                    this.CWagCountField = value;
                    this.RaisePropertyChanged("CWagCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrewStTimeH {
            get {
                return this.CrewStTimeHField;
            }
            set {
                if ((this.CrewStTimeHField.Equals(value) != true)) {
                    this.CrewStTimeHField = value;
                    this.RaisePropertyChanged("CrewStTimeH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrewStTimeM {
            get {
                return this.CrewStTimeMField;
            }
            set {
                if ((this.CrewStTimeMField.Equals(value) != true)) {
                    this.CrewStTimeMField = value;
                    this.RaisePropertyChanged("CrewStTimeM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrWeight {
            get {
                return this.GrWeightField;
            }
            set {
                if ((this.GrWeightField.Equals(value) != true)) {
                    this.GrWeightField = value;
                    this.RaisePropertyChanged("GrWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Machinist {
            get {
                return this.MachinistField;
            }
            set {
                if ((object.ReferenceEquals(this.MachinistField, value) != true)) {
                    this.MachinistField = value;
                    this.RaisePropertyChanged("Machinist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessIdn {
            get {
                return this.MessIdnField;
            }
            set {
                if ((this.MessIdnField.Equals(value) != true)) {
                    this.MessIdnField = value;
                    this.RaisePropertyChanged("MessIdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessProp {
            get {
                return this.MessPropField;
            }
            set {
                if ((this.MessPropField.Equals(value) != true)) {
                    this.MessPropField = value;
                    this.RaisePropertyChanged("MessProp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessStation {
            get {
                return this.MessStationField;
            }
            set {
                if ((object.ReferenceEquals(this.MessStationField, value) != true)) {
                    this.MessStationField = value;
                    this.RaisePropertyChanged("MessStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MessTime {
            get {
                return this.MessTimeField;
            }
            set {
                if ((this.MessTimeField.Equals(value) != true)) {
                    this.MessTimeField = value;
                    this.RaisePropertyChanged("MessTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessType {
            get {
                return this.MessTypeField;
            }
            set {
                if ((this.MessTypeField.Equals(value) != true)) {
                    this.MessTypeField = value;
                    this.RaisePropertyChanged("MessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NmSost {
            get {
                return this.NmSostField;
            }
            set {
                if ((object.ReferenceEquals(this.NmSostField, value) != true)) {
                    this.NmSostField = value;
                    this.RaisePropertyChanged("NmSost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NtWeight {
            get {
                return this.NtWeightField;
            }
            set {
                if ((this.NtWeightField.Equals(value) != true)) {
                    this.NtWeightField = value;
                    this.RaisePropertyChanged("NtWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StDest {
            get {
                return this.StDestField;
            }
            set {
                if ((object.ReferenceEquals(this.StDestField, value) != true)) {
                    this.StDestField = value;
                    this.RaisePropertyChanged("StDest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StForm {
            get {
                return this.StFormField;
            }
            set {
                if ((object.ReferenceEquals(this.StFormField, value) != true)) {
                    this.StFormField = value;
                    this.RaisePropertyChanged("StForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainIdn {
            get {
                return this.TrainIdnField;
            }
            set {
                if ((this.TrainIdnField.Equals(value) != true)) {
                    this.TrainIdnField = value;
                    this.RaisePropertyChanged("TrainIdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNum {
            get {
                return this.TrainNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumField, value) != true)) {
                    this.TrainNumField = value;
                    this.RaisePropertyChanged("TrainNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BindingCommand", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses.Commands")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrafficTrain.ServiceInfoTrainAll.BindTrainThreadsCommnand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrafficTrain.ServiceInfoTrainAll.AssignTrainNumberCommand))]
    public partial class BindingCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BindTrainThreadsCommnand", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses.Commands")]
    [System.SerializableAttribute()]
    public partial class BindTrainThreadsCommnand : TrafficTrain.ServiceInfoTrainAll.BindingCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((this.SourceIdField.Equals(value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((this.TargetIdField.Equals(value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssignTrainNumberCommand", Namespace="http://schemas.datacontract.org/2004/07/NdeDataClasses.Commands")]
    [System.SerializableAttribute()]
    public partial class AssignTrainNumberCommand : TrafficTrain.ServiceInfoTrainAll.BindingCommand {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainNumberSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainThreadIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCode {
            get {
                return this.StationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StationCodeField, value) != true)) {
                    this.StationCodeField = value;
                    this.RaisePropertyChanged("StationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumber {
            get {
                return this.TrainNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberField, value) != true)) {
                    this.TrainNumberField = value;
                    this.RaisePropertyChanged("TrainNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumberPrefix {
            get {
                return this.TrainNumberPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberPrefixField, value) != true)) {
                    this.TrainNumberPrefixField = value;
                    this.RaisePropertyChanged("TrainNumberPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainNumberSuffix {
            get {
                return this.TrainNumberSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainNumberSuffixField, value) != true)) {
                    this.TrainNumberSuffixField = value;
                    this.RaisePropertyChanged("TrainNumberSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainThreadId {
            get {
                return this.TrainThreadIdField;
            }
            set {
                if ((this.TrainThreadIdField.Equals(value) != true)) {
                    this.TrainThreadIdField = value;
                    this.RaisePropertyChanged("TrainThreadId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInfoTrainAll.INdeService")]
    public interface INdeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetLastTrainEvents", ReplyAction="http://tempuri.org/INdeService/GetLastTrainEventsResponse")]
        TrafficTrain.ServiceInfoTrainAll.TrainEvent[] GetLastTrainEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkVectors", ReplyAction="http://tempuri.org/INdeService/GetWorkVectorsResponse")]
        TrafficTrain.ServiceInfoTrainAll.TrainWorking[] GetWorkVectors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/GetWorkMessages", ReplyAction="http://tempuri.org/INdeService/GetWorkMessagesResponse")]
        TrafficTrain.ServiceInfoTrainAll.WorkMessage[] GetWorkMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INdeService/ExecuteBindingCommand", ReplyAction="http://tempuri.org/INdeService/ExecuteBindingCommandResponse")]
        void ExecuteBindingCommand(TrafficTrain.ServiceInfoTrainAll.BindingCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INdeServiceChannel : TrafficTrain.ServiceInfoTrainAll.INdeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NdeServiceClient : System.ServiceModel.ClientBase<TrafficTrain.ServiceInfoTrainAll.INdeService>, TrafficTrain.ServiceInfoTrainAll.INdeService {
        
        public NdeServiceClient() {
        }
        
        public NdeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NdeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrafficTrain.ServiceInfoTrainAll.TrainEvent[] GetLastTrainEvents() {
            return base.Channel.GetLastTrainEvents();
        }
        
        public TrafficTrain.ServiceInfoTrainAll.TrainWorking[] GetWorkVectors() {
            return base.Channel.GetWorkVectors();
        }
        
        public TrafficTrain.ServiceInfoTrainAll.WorkMessage[] GetWorkMessages() {
            return base.Channel.GetWorkMessages();
        }
        
        public void ExecuteBindingCommand(TrafficTrain.ServiceInfoTrainAll.BindingCommand command) {
            base.Channel.ExecuteBindingCommand(command);
        }
    }
}
