//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficTrain.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainEvent", Namespace="http://schemas.datacontract.org/2004/07/AGDP.Common.ModelData")]
    [System.SerializableAttribute()]
    public partial class TrainEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodeESRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdStrageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameRopeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechStopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeDepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainDepartureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodeESR {
            get {
                return this.CodeESRField;
            }
            set {
                if ((this.CodeESRField.Equals(value) != true)) {
                    this.CodeESRField = value;
                    this.RaisePropertyChanged("CodeESR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdObject {
            get {
                return this.IdObjectField;
            }
            set {
                if ((this.IdObjectField.Equals(value) != true)) {
                    this.IdObjectField = value;
                    this.RaisePropertyChanged("IdObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdStrage {
            get {
                return this.IdStrageField;
            }
            set {
                if ((this.IdStrageField.Equals(value) != true)) {
                    this.IdStrageField = value;
                    this.RaisePropertyChanged("IdStrage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamePoint {
            get {
                return this.NamePointField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePointField, value) != true)) {
                    this.NamePointField = value;
                    this.RaisePropertyChanged("NamePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameRope {
            get {
                return this.NameRopeField;
            }
            set {
                if ((object.ReferenceEquals(this.NameRopeField, value) != true)) {
                    this.NameRopeField = value;
                    this.RaisePropertyChanged("NameRope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberArea {
            get {
                return this.NumberAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberAreaField, value) != true)) {
                    this.NumberAreaField = value;
                    this.RaisePropertyChanged("NumberArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechStop {
            get {
                return this.TechStopField;
            }
            set {
                if ((object.ReferenceEquals(this.TechStopField, value) != true)) {
                    this.TechStopField = value;
                    this.RaisePropertyChanged("TechStop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeArrival {
            get {
                return this.TimeArrivalField;
            }
            set {
                if ((this.TimeArrivalField.Equals(value) != true)) {
                    this.TimeArrivalField = value;
                    this.RaisePropertyChanged("TimeArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeDeparture {
            get {
                return this.TimeDepartureField;
            }
            set {
                if ((this.TimeDepartureField.Equals(value) != true)) {
                    this.TimeDepartureField = value;
                    this.RaisePropertyChanged("TimeDeparture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainArea {
            get {
                return this.TrainAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainAreaField, value) != true)) {
                    this.TrainAreaField = value;
                    this.RaisePropertyChanged("TrainArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainDeparture {
            get {
                return this.TrainDepartureField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainDepartureField, value) != true)) {
                    this.TrainDepartureField = value;
                    this.RaisePropertyChanged("TrainDeparture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainId {
            get {
                return this.TrainIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainIdField, value) != true)) {
                    this.TrainIdField = value;
                    this.RaisePropertyChanged("TrainId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTimeTableByArea", ReplyAction="http://tempuri.org/IService/GetTimeTableByAreaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrafficTrain.ServiceReference1.TrainEvent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrafficTrain.ServiceReference1.TrainEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] GetTimeTableByArea(string numberArea, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTimeTableByArea", ReplyAction="http://tempuri.org/IService/GetTimeTableByAreaResponse")]
        System.Threading.Tasks.Task<object[]> GetTimeTableByAreaAsync(string numberArea, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTimeTableByAreaRange", ReplyAction="http://tempuri.org/IService/GetTimeTableByAreaRangeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrafficTrain.ServiceReference1.TrainEvent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TrafficTrain.ServiceReference1.TrainEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        object[] GetTimeTableByAreaRange(string numberArea, System.DateTime dateWindowStart, System.DateTime dateWindowEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTimeTableByAreaRange", ReplyAction="http://tempuri.org/IService/GetTimeTableByAreaRangeResponse")]
        System.Threading.Tasks.Task<object[]> GetTimeTableByAreaRangeAsync(string numberArea, System.DateTime dateWindowStart, System.DateTime dateWindowEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetTimeTableWindow", ReplyAction="http://tempuri.org/IService/SetTimeTableWindowResponse")]
        string[] SetTimeTableWindow(string user, string login, string numberArea, System.DateTime dateWindow, TrafficTrain.ServiceReference1.TrainEvent[] timeTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetTimeTableWindow", ReplyAction="http://tempuri.org/IService/SetTimeTableWindowResponse")]
        System.Threading.Tasks.Task<string[]> SetTimeTableWindowAsync(string user, string login, string numberArea, System.DateTime dateWindow, TrafficTrain.ServiceReference1.TrainEvent[] timeTable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TrafficTrain.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TrafficTrain.ServiceReference1.IService>, TrafficTrain.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object[] GetTimeTableByArea(string numberArea, System.DateTime date) {
            return base.Channel.GetTimeTableByArea(numberArea, date);
        }
        
        public System.Threading.Tasks.Task<object[]> GetTimeTableByAreaAsync(string numberArea, System.DateTime date) {
            return base.Channel.GetTimeTableByAreaAsync(numberArea, date);
        }
        
        public object[] GetTimeTableByAreaRange(string numberArea, System.DateTime dateWindowStart, System.DateTime dateWindowEnd) {
            return base.Channel.GetTimeTableByAreaRange(numberArea, dateWindowStart, dateWindowEnd);
        }
        
        public System.Threading.Tasks.Task<object[]> GetTimeTableByAreaRangeAsync(string numberArea, System.DateTime dateWindowStart, System.DateTime dateWindowEnd) {
            return base.Channel.GetTimeTableByAreaRangeAsync(numberArea, dateWindowStart, dateWindowEnd);
        }
        
        public string[] SetTimeTableWindow(string user, string login, string numberArea, System.DateTime dateWindow, TrafficTrain.ServiceReference1.TrainEvent[] timeTable) {
            return base.Channel.SetTimeTableWindow(user, login, numberArea, dateWindow, timeTable);
        }
        
        public System.Threading.Tasks.Task<string[]> SetTimeTableWindowAsync(string user, string login, string numberArea, System.DateTime dateWindow, TrafficTrain.ServiceReference1.TrainEvent[] timeTable) {
            return base.Channel.SetTimeTableWindowAsync(user, login, numberArea, dateWindow, timeTable);
        }
    }
}
