//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficTrain.ServiceTrainHelp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainInfo", Namespace="http://schemas.datacontract.org/2004/07/MessageTrainService")]
    [System.SerializableAttribute()]
    public partial class TrainInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LenghtTrainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightTrainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LenghtTrain {
            get {
                return this.LenghtTrainField;
            }
            set {
                if ((this.LenghtTrainField.Equals(value) != true)) {
                    this.LenghtTrainField = value;
                    this.RaisePropertyChanged("LenghtTrain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkField, value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationEnd {
            get {
                return this.StationEndField;
            }
            set {
                if ((object.ReferenceEquals(this.StationEndField, value) != true)) {
                    this.StationEndField = value;
                    this.RaisePropertyChanged("StationEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WeightTrain {
            get {
                return this.WeightTrainField;
            }
            set {
                if ((this.WeightTrainField.Equals(value) != true)) {
                    this.WeightTrainField = value;
                    this.RaisePropertyChanged("WeightTrain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTrainHelp.ITrainService")]
    public interface ITrainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetMessageTrains", ReplyAction="http://tempuri.org/ITrainService/GetMessageTrainsResponse")]
        TrafficTrain.ServiceTrainHelp.TrainInfo[] GetMessageTrains(int[] MessageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrainService/GetMessageTrain", ReplyAction="http://tempuri.org/ITrainService/GetMessageTrainResponse")]
        TrafficTrain.ServiceTrainHelp.TrainInfo GetMessageTrain(int MessageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainServiceChannel : TrafficTrain.ServiceTrainHelp.ITrainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainServiceClient : System.ServiceModel.ClientBase<TrafficTrain.ServiceTrainHelp.ITrainService>, TrafficTrain.ServiceTrainHelp.ITrainService {
        
        public TrainServiceClient() {
        }
        
        public TrainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrafficTrain.ServiceTrainHelp.TrainInfo[] GetMessageTrains(int[] MessageIds) {
            return base.Channel.GetMessageTrains(MessageIds);
        }
        
        public TrafficTrain.ServiceTrainHelp.TrainInfo GetMessageTrain(int MessageId) {
            return base.Channel.GetMessageTrain(MessageId);
        }
    }
}
